Xan/sc 24385/tile server
TileDB-Inc/TileDB-BioImaging pull request #60
Opened 2023-01-13 14:17 UTC by XanthosXanthopoulos

Currently we have not any proper data to test the server metadata and slice methods. I set this as a draft since there are no test implemented

2023-01-17 11:12 UTC, gsakkis requested changes
Looks great overall :100:  I left a few code style comments but nothing major.

Two more general comments:
- This doesn't have to be a package (also `utils` is usually a name for internal helpers). A plain `tiledb/bioimg/tiles_server.py` script will do.
- It should be packaged as an optional dependency and its dependencies (flask etc) be added to `extras_require` in setup.py.

2023-01-17 11:12 UTC, gsakkis commented on tiledb/bioimg/utils/tiles_server.py
> +        self, host: str = "0.0.0.0", port: int = 8000, multiprocess: bool = False
Generalize `multiprocess: bool = False` to `num_processes: int = 0`

2023-01-17 11:12 UTC, gsakkis commented on tiledb/bioimg/utils/tiles_server.py
> +        print(platform.system())
leftover print

2023-01-17 11:12 UTC, gsakkis commented on tiledb/bioimg/utils/tiles_server.py
> +            self._pool.apply_async(self._app.run, kwds={"host": host, "port": port})
What's wrong with `run_simple` on Windows?

2023-01-17 11:26 UTC, gsakkis commented on tiledb/bioimg/utils/tiles_server.py
> +from multiprocess import Pool
`s/multiprocess/multiprocessing`

2023-02-07 15:55 UTC, XanthosXanthopoulos commented
The tile server will not be used for now so the PR closed

2023-02-07 15:55 UTC, closed without merging